import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GTProvider } from 'gt-next';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GT Test App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <GTProvider
      apiKey={process.env.NEXT_PUBLIC_GT_API_KEY}
      projectId={process.env.NEXT_PUBLIC_GT_PROJECT_ID}
      defaultLocale="en"
    >
      {children}
    </GTProvider>
      </body>
    </html>
  );
}
